### ISSUE TITLE
log.txt

### ISSUE THREAD

**Issue by aa1008611** [MTProto/MTProtoProxy#14]
Connecting...
view log

tail log.txt
  id: 67,
  bytesWritten: 4198,
  bytesRead: 517,
  error: 'Error: client timedout\n' +
    '    at Socket.<anonymous> (https://raw.githubusercontent.com/MTProto/MTProtoProxy/master/mtprotoproxy.js:302:53)\n' +
    '    at Socket.emit (events.js:210:5)\n' +
    '    at Socket._onTimeout (net.js:468:8)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
} on core  1

**Comment by aa1008611** [comment]
New client: {
  id: 91,
  address: '183.××.××.××',
  port: 60723,
  secretIndex: 0,
  SNI: '\u0000+'
} on core  1
(node:27464) UnhandledPromiseRejectionWarning: Error: Assertion failed:
(node:27464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 196)
Client left: { id: 90, bytesWritten: 4983, bytesRead: 4502 } on core  1

**Comment by aa1008611** [comment]
It is easy to encounter situations where the connection cannot be made
