### ISSUE TITLE
fake tls

### ISSUE THREAD

**Issue by ZarinNegah** [MTProto/MTProtoProxy#3]
hi
good time
please add fake-tls to your nodejs script

https://github.com/HirbodBehnam/MTProtoProxyInstaller
and
https://github.com/seriyps/mtproto_proxy

Also like the above scripts , is it possible to build an automatic installer and config port and secret or secrets and tag?

**Comment by MTProto** [comment]
Hi, the support was added. Some APIs have changed. I will try to add an automatic installer in future in other repositories. But currently this repository is aimed at only creating a module. This module is for programmers only.

**Comment by ZarinNegah** [comment]
Hello
Thanks for the update
I'm waiting for another repository for automatic installation

**Comment by MTProto** [comment]
I have added a fast set-up part. Could you please test it and tell me your opinion?

**Comment by ZarinNegah** [comment]
Hello
Yes,thanks you
Installed and enabled
But the installation needs to be more automated
And also select more and multi secret
You can use the example below to build more
https://git.io/fjo3u

**Comment by MTProto** [comment]
It supports multi secret. Just separate secrets with space.

**Comment by MTProto** [comment]
It does not need root access nor it requires to install any package. May be setting firewall requires root password.

**Comment by ZarinNegah** [comment]
Thankful
For you too, the number of connections increases, ping increases

**Comment by MTProto** [comment]
I have not tested it under severe conditions. Currently it uses inter-process communication to create reports of each process. num_cpus should always be less than or equal to your cpu cores. Please tell me your experience with this proxy. Also remember that you can access the report through web. Full report is enabled by default and you can access it by log1.txt in the current directory.

**Comment by ZarinNegah** [comment]
After a few minutes it will be disconnected and you will need to resubmit the following command to activate it
bash ./fastsetup.sh

**Comment by ZarinNegah** [comment]
ping increases

**Comment by MTProto** [comment]
After it terminated, just check the log file by typing "tail log.txt".

**Comment by MTProto** [comment]
عزیز اگر ایرادی داشت بهم بگو اصلاح کنم. چون برای من مشکلی پیش نمیاد. فقط یه مساله. اگر سرعت کامپیوترت خیلی کم باشه، سیستم عامل به برنامه سیگنال
 SIGXCPU
 میفرسته که البته این سیگنال نود رو میبنده چون من هندلش نکردم. فکر کنم ایراد از اون باشه که برنامه بسته میشه. این ایراد را خیلی راحت میتونم برطرف کنم. اگر بتونی فایل لاگ رو ببینی و بهم بگی چه خبره توش میتونم راحتتر عیب احتمالی کد رو تشخیص بدم.
در مورد زیاد شدن پینگ هم برای من مشکلی نداره. باید روش کار کنم ببینم دلیل چیه که برای شما پینگ زیاد میشه. این کد چند هسته ای رو قدیم دادم به یکی اونم همین ایراد رو گفت. شاید کلا چند هسته ای رو حذف کنم.

**Comment by ZarinNegah** [comment]
نمیدونستم ایرانی هستین
بی زحمت به تلگرامم پیام بدید
@MTProtoConfiger

**Comment by gost-serb** [comment]
Hi. Thanks for cool proxy!
For some reason, I'm facing error while trying to connect to my proxy via fake-tls.

Here is error message:
```
 Client left: {
  id: 262,
  bytesWritten: 0,
  bytesRead: 132,
  error: 'Error: Assertion failed: No matching secret\n' +
    '    at assertit (/mtproxy/node_modules/mtprotoproxy/index.js:110:9)\n' +
    '    at handleClient (/mtproxy/node_modules/mtprotoproxy/index.js:655:2)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)'
} on core  2
```

I event tried with default secret: `ee00000000000000000000000000000000` in server config, and `ee00000000000000000000000000000000676f6f676c652e636f6d` on client side. At the same dd secret works fine.

Any ideas?

**Comment by MTProto** [comment]
Everything seems OK. Have you updated your telegram client? Please install the most recent version of Telegram. Then double check the secret entered to your client. Remember there are 32 consecutive  ('0')'s. Please note that this is not an error message, In fact this is the reason for disconnecting client. It's meaning is simple. A client is trying to connect, but it's secret does not match with any of the secrets provided to the proxy. In fact from the proxy point of view, the user was not legitimate to use the proxy. 
If you solved the problem, please let us know the reason, even if you made the mistake.

**Comment by gost-serb** [comment]
I used latest version of telegram client (also checked on official mobile client). I think problem occurred because server runs in corporate network with firewall which inserts itself as the trusted host for SSL connections.

**Comment by masoudzeeb** [comment]
سلام عزیز
این اول سکرت کد که dd و ee رو اضافه که میکنیم
از 32 کارکتر به 35 کارکتر تبدیل میشه
وقتی میخوای کانال اسپانسری رو در بات MTProxy واردکنیم
خطا میده که سکرت کد باید 32 کارکتر باشه

**Comment by MTProto** [comment]
> سلام عزیز
این اول سکرت کد که dd و ee رو اضافه که میکنیم
از 32 کارکتر به 35 کارکتر تبدیل میشه
وقتی میخوای کانال اسپانسری رو در بات MTProxy واردکنیم
خطا میده که سکرت کد باید 32 کارکتر باشه

If you add those two characters to secrets, they would become 34 hex characters. (32+2=34). I think you are adding [SPACE] in between.

**Comment by masoudzeeb** [comment]
بله میشه 34 تا اشتباه زدم
ولی موقع ثبت در کانال Mtproto خطا میده
نمیشه این dd و ee رو حذف کرد ؟

یا داخل کد تعداد رو از 34 به 32 تغییر داد که اتصال انجام بشه ؟

**Comment by MTProto** [comment]
It is not important what you enter inside mtproto bot. Just fill it with 32 consecutive '0's. Although technically this problem should not occur.

**Comment by masoudzeeb** [comment]
Since yesterday, ASPs have been denied access to the server by secret code
Where should we change the code mtprotoproxy.js to increase the secret size of the code?

**Comment by masoudzeeb** [comment]
از دیروز تا به حال ای اس پی ها بر اساس سایز سکرت کد پروتکل رو تشخص میدند و اجازه دسترسی به سرور رو نمیدند
کجای کد mtprotoproxy.js رو باید تغییر بدیم تا سایز سکرت کد رو بیشتر کنیم ؟

**Comment by MTProto** [comment]
The size of the secret can not be changed as it is a part of protocol specification, and telegram server would not accept that. Besides, the protocol is already encrypting and padding, there is no need to change the size of packets as it is already implemented. Protocol can not be distinguished from TLS protocol. Choose a suitable SNI and port 443.

**Comment by masoudzeeb** [comment]
خیلی از پروکسی هایی که الان در حال استفاده هستند از سکرت کد 66 کارکتر استفاده میکنند
طبق بررسی ها اینجانب سکرت کد بین سرور و سرور تلگرام قابل تغییر نیست ولی سکرت کد بین کلاینت و سرور قابل تغییر هستش

**Comment by masoudzeeb** [comment]
تمام سکرت کد هایی که 32 تا 34 کارکتر بوده آی پی هاش فیلتر شده ولی سکرت کد های 66 کارکتر هیچ کدوم فیلتر نشدند

**Comment by masoudzeeb** [comment]
Many proxies in use now use the 66-character secret
According to the reviews, the secret code cannot be changed between the server and the telegram server, but the secret code can be changed between the client and the server.

All scripts with 32 to 34 characters were filtered by IPs, but 66 characters were not filtered by any

**Comment by VAHID002AM** [comment]
سلام وقت بخیر 
ببخشید پشتیبانی میتونه فارسی حرف بزنه؟
